version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_USER:     root
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE:      development
      MYSQL_USER:          gessy0129
      MYSQL_PASSWORD:      gessy_password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes_from:
      - datastore
  search:
    entrypoint: /entrypoints/elasticsearch.sh
    image: elasticsearch:2.4
    ports:
      - '29200:9200'
      - '29300:9300'
    volumes:
      - ./entrypoints:/entrypoints
  datastore:
    image: busybox
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    command: bundle exec rails s WEBrick -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:root_password@db/development
      SEARCHBOX_SSL_URL: http://search:9200
      ELASTICSEARCH_URL: http://search:9200
      AWS_ACCESS_KEY_ID: sample
      AWS_SECRET_ACCESS_KEY: sample
      AWS_REGION: us-west-2
    volumes:
      - .:/myapp
    volumes_from:
      - datastore
    ports:
      - 3000:3000
    links:
      - db
      - search
volumes:
  mysql-data:
    driver: local

